#==============================
#      STRING VALUES
#==============================
string_value = "Hello, World!"
#==============================


#==============================
#      INTEGERS VALUES
#==============================
int_value = 42
#==============================


#==============================
#        BOOLEAN VALUES
#==============================
boolean_value = true
#==============================


#==============================
#        FLOAT VALUES
#==============================
float_value = 3.14
#==============================


#==============================
#    ARRAY OF STRING VALUES
#==============================
string_array = ["apple", "banana", "orange"]
#==============================


#==============================
#    ARRAY OF INTEGERS VALUES
#==============================
int_array = [1, 2, 3, 4, 5]
#==============================


#==============================
#   ARRAY OF FLOAT VALUES
#==============================
float_array = [1.1, 2.2, 3.3, 4.4, 5.5]
#==============================


#==============================
#    ARRAY OF BOOLEAN VALUES
#==============================
bool_array = [true, false, true, true]
#==============================


#==============================
#     2D ARRAY OF INTEGERS
#==============================
two_d_int_array = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
#==============================


#==============================
#       STRUCTURE
#==============================
[structure]
name = "John"  # Name field of the structure
age = 30       # Age field of the structure
#==============================


#==============================
#      ARRAY OF STRUCTURE
#==============================
[[struct_array]]
name = "Alice"  # Name field of the first structure
age = 25        # Age field of the first structure

[[struct_array]]
name = "Bob"    # Name field of the second structure
age = 35        # Age field of the second structure
#==============================